export const COUNTRY = {
    GET_SEARCHED : "GET_SEARCHED",
    EMPTY_LIST : "EMPTY_LIST",
    GET_ERROR_MESSAGE: "GET_ERROR_MESSAGE",
    SET_SEARCH_WORD: "SET_SEARCH_WORD",
    SET_SKIP: "SET_SKIP",
    SET_CATEGORY: "SET_CATEGORY",
    SET_LIMIT: "SET_LIMIT",
    SET_SORTING: "SET_SORTING"
}